#!/usr/bin/env bash

/bin/java \
	-Declipse.application=org.eclipse.jdt.ls.core.id1 \
	-Dosgi.bundles.defaultStartLevel=4 \
	-Declipse.product=org.eclipse.jdt.ls.core.product \
	-Dlog.level=ALL \
	-noverify \
	-Xmx1G \
	-jar ~/dev/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210908-1257.jar  \
	-configuration ~/dev/jdtls/config_linux \
	-data ~/dev/jdtls/workspace\
	--add-modules=ALL-SYSTEM \
	--add-opens java.base/java.util=ALL-UNNAMED \
	--add-opens java.base/java.lang=ALL-UNNAMED
